Fernando/avaliacao primeira edicao
cciuenf/introducao_linha_de_comando pull request #13
Opened 2021-05-26 19:18 UTC by Nandolinhares

2021-05-26 19:23 UTC, Mdsp9070 requested changes
boa!

só o arquivo de historico que está errado! sua PR é a sexta aberta, seu nome deveria estar na segunda tabela, segunda coluna

2021-05-26 19:23 UTC, Nandolinhares commented
@Mdsp9070 atualizeio

2021-05-26 19:41 UTC, Mdsp9070 approved these changes
boa! desculpa qq coisa (:

2021-05-28 19:47 UTC, Mdsp9070 approved these changes

2021-05-28 19:47 UTC, Mdsp9070 commented on primeira_edicao/trabalhos_alunos/fernando_linhares/respostas-scripts/docker/Dockerfile
> +CMD ["nginx", "-g", "daemon off;"]
brabo kkkkk

2021-05-28 19:47 UTC, Mdsp9070 commented on primeira_edicao/trabalhos_alunos/fernando_linhares/respostas-scripts/shell/comando.sh
> +fi
faltou só os comments haha

2021-05-28 19:48 UTC, merged

2021-05-28 19:49 UTC, Mdsp9070 commented
boa!

![image](https://user-images.githubusercontent.com/44469426/120035265-ab217280-bfd4-11eb-9b8e-291ef6862dc2.png)

2021-05-28 20:10 UTC, Nandolinhares commented on primeira_edicao/trabalhos_alunos/fernando_linhares/respostas-scripts/shell/comando.sh
> +fi
hahah esqueci mesmo