Leonardo/avaliacao primeira edicao
cciuenf/introducao_linha_de_comando pull request #21
Opened 2021-05-26 19:39 UTC by Leonardondm

2021-05-26 19:41 UTC, Leonardondm commented
Na hora que dei a PR nao reparei que nao tava na main, mas agora deve ta certo.

2021-05-26 19:50 UTC, Mdsp9070 requested changes
boa!

mas o arquivo de historico continua errado!

abriram mais PRs, então seu nome tem que estar na terceira tabela, quarta coluna!

tipo:

```
|   |   |   |   |
|---+---+---+---|
|   |   |   |   |
|   |   |   |   |
|   |   |   |   |

|   |   |   |   |
|---+---+---+---|
|   |   |   |   |
|   |   |   |   |
|   |   |   |   |

|   |   |   |  xxxxx  |
|---+---+---+---|
|   |   |   |  xxxxx  |
|   |   |   |   |
|   |   |   |   |
```

2021-05-26 19:53 UTC, Leonardondm commented
Fiz a modificação diz pra mim se ficou certo

2021-05-29 17:13 UTC, Mdsp9070 approved these changes

2021-05-29 17:15 UTC, Mdsp9070 commented
boa!

![image](https://user-images.githubusercontent.com/44469426/120078977-4a537200-c088-11eb-8b8f-abe198deec9d.png)

alguma dica ou sugestõ para a próxima edição?

2021-05-29 17:15 UTC, merged