change commands to code notation to fix dash problem - notas_de_aula 6
cciuenf/introducao_linha_de_comando pull request #3
Opened 2021-05-06 18:57 UTC by pedrohb88

O double dash do comando `git --amend` tava ficando bugado e parecendo ser um dash só. 

Marcar os comandos como `código` resolveu o problema :)

2021-05-09 00:34 UTC, Mdsp9070 commented
obrigado pela PR (: 💙 💛 💜 💚 

porém, essas modificações quebram o padrão dos outros títulos \:

talvez se todos os títulos com comandos do arquivo fossem mudados para marcação de `código` fosse mais interessante

o que acha disso?

2021-05-14 23:35 UTC, Mdsp9070 commented
Perante a nova hierarquia de diretórios definida a partir [desta mesclagem](2990cf0abdf9be7bd85581154747eae9cc3b706b), sugiro a atualização desta PR.

2021-05-17 15:56 UTC, Mdsp9070 requested changes
Por favor, leia os comentários acima e compartilhe sua opinião (:

2021-05-17 18:31 UTC, pedrohb88 commented
Opa, foi mal, tô atolado com outras coisas aqui. Só tinha aberto o PR como uma correção rápida e pequena em algo que pode confundir uma galera. Vou fechar ele aqui, mas qualquer coisa é só me dar um toque.

2021-05-17 18:31 UTC, closed without merging

2021-05-18 01:26 UTC, Mdsp9070 commented
sem problemas!